# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true


# all available settings of specific linters
linters-settings:
  govet:
    # report about shadowed variables
    check-shadowing: true
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0.8
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: gitlab.com/slon/shad-go
  stylecheck:
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1018"]

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - stylecheck
    - gosimple
    - govet
    - ineffassign
    - exportloopref
    - staticcheck
    - typecheck
    - unconvert
